### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by Kx96xx** [swagkarna/Netflix-Scam-Page#1]
Hey man. Just wanted to point out that everything works as expected in 000webhost; however, when I want to test it on another hosting site such as hostinger, it doesn't send the cc information anymore. I tried changing the code a bit, but it still doesn't work. Lemme know if there's any info you need so it can be resolved. 

Regards,
Kx96xx

**Comment by swagkarna** [comment]
Refer this link  [https://bit.ly/3hVS7YT](url)
